### ISSUE TITLE
A bit worried about lacunae

### ISSUE THREAD

**Issue by hcayless** [DigitalLatin/guidelines#1]
In https://github.com/DigitalLatin/guidelines/blob/master/LDLT-Guidelines.xml#L2777-L2815, I don't think lacunaStart/End is the way to do this if the gap is indicated in the main text. I would use `<gap reason="lost" extent="unknown">` or `@extent="33" unit="chapter"` or something like that. The lacunaStart/End elements, like the witStart/End elements, are for indicating where in the main text particular fragmentary witnesses start and stop. This is not, I think, something that's consistently done in the apparatus in print (though there might be a note to the effect that "witness X starts here, or is missing this section, etc."). It's more likely to be covered in the front matter, and you'd just see the siglum for that witness pick up and drop off in the app. crit.

**Comment by sjhuskey** [comment]
As it happens, I’ve been discussing this with Cynthia Damon, whose text I used as an example. I need to make two sections: actual lacuna in the entire tradition and gap in one witness.

—Sam

**Comment by sjhuskey** [comment]
I have added sections on actual lacunae and gaps in witnesses, along with the presence of fragmentary witnesses.
