### ISSUE TITLE
copyOf in 5.10.2?

### ISSUE THREAD

**Issue by hcayless** [DigitalLatin/guidelines#2]
Might it be better to use `@copyOf` instead of repeating the text? Also, now that we have `@require`, we can do this a bit more simply, and, finally, I might refactor things, because the choices are between 2 lines, 2 lines with transposed half-lines, and one line. I'm not sure I've made it any simpler :-(

``` xml
<app>
  <lem>
    <l n="304"><app><lem xml:id="lem-304-nat">nat lupus inter oues,</lem></app> <app>
      <lem xml:id="lem-304-fuluos"
        require="#lem-305-unda">fuluos uehit unda
        leones,</lem>
      <rdg wit="#Bern" xml:id="rdg-304-Bern"
        require="#rdg-305-Bern" copyOf="#lem-305-nec"/>
    </app></l>
    <l n="305">unda uehit tigres; <app>
      <lem xml:id="lem-305-nec"
        require="#lem-304-nat">nec uires fulminis apro</lem>
      <rdg wit="#Bern" xml:id="rdg-305-Bern"
        require="#rdg-304-Bern" copyOf="#lem-304-fuluos"/>
    </app></l></lem>
  <rdg wit="#H #M" xml:id="rdg-305-HM"
      require="#rdg-304-HM">
      <l n="304/5"><join target="#lem-304-nat #lem-305-nec"/></l>
  </rdg>
  <witDetail wit="#M" target="#rdg-304-HM"
        type="ante-corr"><hi rend="superscript">ac</hi>(N<hi rend="superscript">ac</hi></witDetail>
</app>
```

**Comment by sjhuskey** [comment]
So @exclude is not needed at all here? I've been using both @exclude and @require, but I have suspected that doing that is a belt-and-suspenders approach.

**Comment by sjhuskey** [comment]
I think your way is preferable, but I think there's an extraneous @require. That is, rdg-304-HM no longer exists. Also, the @target for the <witDetail> should be #rdg-305-HM.

**Comment by sjhuskey** [comment]
I think we've got this nailed down now, so I'm closing the issue.
