### ISSUE TITLE
Should <sic>/<corr> substitutions be character- or word-based?

### ISSUE THREAD

**Issue by adunning** [DigitalLatin/guidelines#33]
The guidelines allow TEI `<sic>`/`<corr>` structures, which is excellent when using a particular witness as a base text and correcting it. It might be worth addressing whether this can be used on a character- rather than word-level (as all the examples do right now): EpiDoc allows it, but I want to be sure it isn't going to create rendering issues.

Character-level substitutions are easier to encode, and useful for some particularly complex situations. Here is one example:

```xml
barsabba<choice><sic><subst><del rend="expunct"><subst><del rend="strikethrough">m</del><add place="inline">n</add></subst></del><add place="above">s</add></subst></sic><corr source="#s">n</corr></choice>
```

- The manuscript originally read 'barsabbam', was changed to 'barsabban', and someone else later modified it to 'barsabbas'.
- The correct reading is 'barsabban' (as reflected in an edition, S).

**Comment by sjhuskey** [comment]
It is the editor's decision to do character-based or word-based substitutions. If it doesn't render correctly, it's a bug that will have to be fixed.

**Comment by adunning** [comment]
Excellent; thanks!
